/**
 * The frame model: an animation as an ordered list of frames, each a set of strokes held for a
 * whole number of ticks.
 *
 * Flipnote Studio's model, which this follows, is deliberately small: a flipbook is a list of
 * pages played at one of a few speeds, each page shown for one tick, with "hold" made by
 * duplicating a page. We keep the list and the single speed, and make hold a per-frame count
 * instead of duplicates, because on the reMarkable a duplicate frame is a whole notebook page
 * (docs/investigations/codrawer-animate.md, "Data model": one page per frame) and because a
 * held frame costs the e-ink preview nothing (it does not refresh, see {@link deviceSchedule}).
 *
 * A frame is a page in the sense of ADR 008: it has a stable id and its strokes are the page's
 * strokes. For frames drawn on the tablet, `source` names the xochitl page that holds them; the
 * strokes here are the latest snapshot the bridge read from that page's `.rm` file. For frames
 * drawn on a phone or generated by an agent, the strokes live only here (and in the router).
 *
 * Everything is a pure function of plain data: operations return a new {@link Anim} and never
 * mutate their input, so the same reducer runs in the app, a router and a test.
 *
 * Units: coordinates are normalised page coordinates (x, y in 0..1 of the page's width and
 * height, ADR 008 / docs/protocol.md); pressure is 0..1; times are milliseconds; `fps` is ticks
 * per second.
 */

/** A point: normalised x, y and pressure 0..1. */
export type Pt = [x: number, y: number, p: number]

/** A committed stroke (ADR 008's stroke, the fields an animation needs). */
export interface AnimStroke {
  /** stable id: the `.rm` CrdtId for tablet ink, the sender's id otherwise */
  id: string
  pts: Pt[]
  /** `#rrggbb[aa]`; absent: the viewer's ink colour */
  color?: string
  /** the tool's thickness setting (reMarkable `thickness_scale`) */
  size?: number
  tool?: string
  author?: string
  /** `agent` for generated ink (in-betweens, motion), ADR 003 */
  provenance?: 'human' | 'agent'
}

/** Where a frame's strokes live on the tablet: a xochitl document and page. */
export interface FrameSource {
  doc: string
  page: string
}

export interface Frame {
  id: string
  /** how many ticks the frame is shown for; an integer ≥ 1 */
  hold: number
  strokes: AnimStroke[]
  /** a key frame (drawn by a person) rather than an in-between */
  key?: boolean
  source?: FrameSource
}

/** How playback continues at the last frame. */
export type LoopMode = 'once' | 'loop' | 'pingpong'

export interface Anim {
  id: string
  title: string
  /** ticks per second; Flipnote's speeds were 0.5, 1, 2, 4, 6, 8, 12, 20, 24 and 30 */
  fps: number
  loop: LoopMode
  frames: Frame[]
}

/** The speeds offered in the UI, ticks per second (Flipnote's ladder). */
export const SPEEDS = [0.5, 1, 2, 4, 6, 8, 12, 20, 24, 30] as const

export const DEFAULT_FPS = 8

// ------------------------------------------------------------------------------------------------
// Construction and editing
// ------------------------------------------------------------------------------------------------

export function emptyFrame(id: string, hold = 1): Frame {
  return { id, hold, strokes: [], key: true }
}

/** A new animation with one empty frame. */
export function createAnim(id: string, title: string, firstFrameId: string, fps = DEFAULT_FPS): Anim {
  return { id, title, fps, loop: 'loop', frames: [emptyFrame(firstFrameId)] }
}

/** The index of a frame by id, or -1. */
export function frameIndex(anim: Anim, id: string): number {
  return anim.frames.findIndex((f) => f.id === id)
}

function requireIndex(anim: Anim, i: number): void {
  if (!Number.isInteger(i) || i < 0 || i >= anim.frames.length) throw new RangeError(`no frame ${i} (have ${anim.frames.length})`)
}

function requireNewId(anim: Anim, id: string): void {
  if (frameIndex(anim, id) >= 0) throw new Error(`frame id ${id} already exists`)
}

/** Insert `frame` after index `after` (-1 inserts at the start). */
export function insertFrame(anim: Anim, after: number, frame: Frame): Anim {
  if (after !== -1) requireIndex(anim, after)
  requireNewId(anim, frame.id)
  const frames = anim.frames.slice()
  frames.splice(after + 1, 0, { ...frame, hold: clampHold(frame.hold) })
  return { ...anim, frames }
}

/** Insert an empty key frame after index `after`. */
export function addFrame(anim: Anim, after: number, id: string): Anim {
  return insertFrame(anim, after, emptyFrame(id))
}

/**
 * Copy frame `i` (its strokes under new ids `<newId>/<n>`) to just after it. Flipnote's most-used
 * command: duplicate, then change a little.
 */
export function duplicateFrame(anim: Anim, i: number, newId: string): Anim {
  requireIndex(anim, i)
  const src = anim.frames[i]
  const copy: Frame = {
    ...src,
    id: newId,
    source: undefined,
    strokes: src.strokes.map((s, n) => ({ ...s, id: `${newId}/${n}`, pts: s.pts.map((p) => [...p] as Pt) })),
  }
  return insertFrame(anim, i, copy)
}

/** Remove frame `i`. The last frame cannot be deleted (an animation always has one). */
export function deleteFrame(anim: Anim, i: number): Anim {
  requireIndex(anim, i)
  if (anim.frames.length === 1) throw new Error('cannot delete the only frame')
  return { ...anim, frames: anim.frames.filter((_, k) => k !== i) }
}

/** Move frame `from` so that it ends up at index `to`. */
export function moveFrame(anim: Anim, from: number, to: number): Anim {
  requireIndex(anim, from)
  requireIndex(anim, to)
  const frames = anim.frames.slice()
  const [f] = frames.splice(from, 1)
  frames.splice(to, 0, f)
  return { ...anim, frames }
}

function clampHold(h: number): number {
  return Math.max(1, Math.min(600, Math.round(Number.isFinite(h) ? h : 1)))
}

export function setHold(anim: Anim, i: number, hold: number): Anim {
  requireIndex(anim, i)
  return { ...anim, frames: anim.frames.map((f, k) => (k === i ? { ...f, hold: clampHold(hold) } : f)) }
}

/** Replace a frame's strokes (a new snapshot of its page arrived, or an agent filled it). */
export function setStrokes(anim: Anim, i: number, strokes: AnimStroke[]): Anim {
  requireIndex(anim, i)
  return { ...anim, frames: anim.frames.map((f, k) => (k === i ? { ...f, strokes } : f)) }
}

export function setFps(anim: Anim, fps: number): Anim {
  if (!(fps > 0 && fps <= 60)) throw new RangeError(`fps ${fps} outside (0, 60]`)
  return { ...anim, fps }
}

export function setLoop(anim: Anim, loop: LoopMode): Anim {
  return { ...anim, loop }
}

// ------------------------------------------------------------------------------------------------
// Timing
// ------------------------------------------------------------------------------------------------

/**
 * The frame indices of one pass of playback, one entry per frame (not per tick). `pingpong` runs
 * forward then back without repeating the end frames (0 1 2 3 2 1), so that looping it has no
 * stutter at either end; `once` and `loop` are the frames in order.
 */
export function passOrder(anim: Anim): number[] {
  const n = anim.frames.length
  const fwd = Array.from({ length: n }, (_, i) => i)
  if (anim.loop !== 'pingpong' || n < 3) return fwd
  return fwd.concat(fwd.slice(1, -1).reverse())
}

/** The length of one pass in ticks (holds included). */
export function passTicks(anim: Anim): number {
  return passOrder(anim).reduce((s, i) => s + anim.frames[i].hold, 0)
}

/** The length of one pass in ms. */
export function passMs(anim: Anim): number {
  return (passTicks(anim) * 1000) / anim.fps
}

/**
 * Which frame is on screen `ms` after playback started. `once` stops on the last frame; the
 * looping modes wrap. Negative times show the first frame.
 */
export function frameAt(anim: Anim, ms: number): number {
  const order = passOrder(anim)
  const total = passTicks(anim)
  let tick = Math.floor((Math.max(0, ms) * anim.fps) / 1000)
  if (anim.loop === 'once') {
    if (tick >= total) return order[order.length - 1]
  } else {
    tick %= total
  }
  for (const i of order) {
    if (tick < anim.frames[i].hold) return i
    tick -= anim.frames[i].hold
  }
  return order[order.length - 1]
}

/** One step of a device's playback: show frame `frame` for `ms`. */
export interface Shown {
  frame: number
  ms: number
}

/**
 * What a slow display should show for one pass, given the fastest rate at which it can change
 * (`deviceFps`, e.g. 4–6 on the Paper Pro's Animation waveform, ~3–5 on the G2 lens).
 *
 * The animation keeps its own clock: a display that cannot keep up drops frames rather than
 * slowing the animation down, so a walk cycle still takes the time it takes. The display is
 * sampled at its own rate; consecutive samples that land on the same frame merge into one step,
 * because on e-ink a refresh that changes nothing still costs a waveform (and on the glasses a
 * ~200 ms image send, ADR 006). If the animation is slower than the device, every frame is shown
 * for exactly its hold.
 */
export function deviceSchedule(anim: Anim, deviceFps: number): Shown[] {
  const total = passMs(anim)
  const out: Shown[] = []
  if (deviceFps >= anim.fps) {
    for (const i of passOrder(anim)) out.push({ frame: i, ms: (anim.frames[i].hold * 1000) / anim.fps })
  } else {
    const step = 1000 / deviceFps
    for (let t = 0; t < total - 1e-9; t += step) {
      const frame = frameAt(anim, t)
      const ms = Math.min(step, total - t)
      const last = out[out.length - 1]
      if (last && last.frame === frame) last.ms += ms
      else out.push({ frame, ms })
    }
  }
  return mergeAdjacent(out)
}

function mergeAdjacent(steps: Shown[]): Shown[] {
  const out: Shown[] = []
  for (const s of steps) {
    const last = out[out.length - 1]
    if (last && last.frame === s.frame) last.ms += s.ms
    else out.push({ ...s })
  }
  return out
}
